// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package oss

import (
	types "cto-github.cisco.com/NFV-BU/go-msx/types"
	mock "github.com/stretchr/testify/mock"
)

// MockOss is an autogenerated mock type for the Api type
type MockOss struct {
	mock.Mock
}

// GetAccessibleServices provides a mock function with given fields:
func (_m *MockOss) GetAccessibleServices() (ServicesResponse, error) {
	ret := _m.Called()

	var r0 ServicesResponse
	if rf, ok := ret.Get(0).(func() ServicesResponse); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(ServicesResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllowedValues provides a mock function with given fields: serviceId, propertyName
func (_m *MockOss) GetAllowedValues(serviceId string, propertyName string) (AllowedValuesResponse, error) {
	ret := _m.Called(serviceId, propertyName)

	var r0 AllowedValuesResponse
	if rf, ok := ret.Get(0).(func(string, string) AllowedValuesResponse); ok {
		r0 = rf(serviceId, propertyName)
	} else {
		r0 = ret.Get(0).(AllowedValuesResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(serviceId, propertyName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPricePlanOptions provides a mock function with given fields: serviceId, offerId, options
func (_m *MockOss) GetPricePlanOptions(serviceId types.UUID, offerId types.UUID, options PricingOptionsRequest) (PricingOptionsResponse, error) {
	ret := _m.Called(serviceId, offerId, options)

	var r0 PricingOptionsResponse
	if rf, ok := ret.Get(0).(func(types.UUID, types.UUID, PricingOptionsRequest) PricingOptionsResponse); ok {
		r0 = rf(serviceId, offerId, options)
	} else {
		r0 = ret.Get(0).(PricingOptionsResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(types.UUID, types.UUID, PricingOptionsRequest) error); ok {
		r1 = rf(serviceId, offerId, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
