// Code generated by mockery v2.3.0. DO NOT EDIT.

package platform

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	msx_platform_client "cto-github.cisco.com/NFV-BU/msx-platform-go-client"
)

// MockDeviceTemplatesApi is an autogenerated mock type for the DeviceTemplatesApi type
type MockDeviceTemplatesApi struct {
	mock.Mock
}

// CreateDeviceTemplate provides a mock function with given fields: ctx, deviceTemplateCreate
func (_m *MockDeviceTemplatesApi) CreateDeviceTemplate(ctx context.Context, deviceTemplateCreate msx_platform_client.DeviceTemplateCreate) (msx_platform_client.DeviceTemplate, *http.Response, error) {
	ret := _m.Called(ctx, deviceTemplateCreate)

	var r0 msx_platform_client.DeviceTemplate
	if rf, ok := ret.Get(0).(func(context.Context, msx_platform_client.DeviceTemplateCreate) msx_platform_client.DeviceTemplate); ok {
		r0 = rf(ctx, deviceTemplateCreate)
	} else {
		r0 = ret.Get(0).(msx_platform_client.DeviceTemplate)
	}

	var r1 *http.Response
	if rf, ok := ret.Get(1).(func(context.Context, msx_platform_client.DeviceTemplateCreate) *http.Response); ok {
		r1 = rf(ctx, deviceTemplateCreate)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, msx_platform_client.DeviceTemplateCreate) error); ok {
		r2 = rf(ctx, deviceTemplateCreate)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// DeleteDeviceTemplate provides a mock function with given fields: ctx, id
func (_m *MockDeviceTemplatesApi) DeleteDeviceTemplate(ctx context.Context, id string) (*http.Response, error) {
	ret := _m.Called(ctx, id)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(context.Context, string) *http.Response); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDeviceTemplate provides a mock function with given fields: ctx, id
func (_m *MockDeviceTemplatesApi) GetDeviceTemplate(ctx context.Context, id string) (msx_platform_client.DeviceTemplate, *http.Response, error) {
	ret := _m.Called(ctx, id)

	var r0 msx_platform_client.DeviceTemplate
	if rf, ok := ret.Get(0).(func(context.Context, string) msx_platform_client.DeviceTemplate); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(msx_platform_client.DeviceTemplate)
	}

	var r1 *http.Response
	if rf, ok := ret.Get(1).(func(context.Context, string) *http.Response); ok {
		r1 = rf(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetDeviceTemplatesList provides a mock function with given fields: ctx, localVarOptionals
func (_m *MockDeviceTemplatesApi) GetDeviceTemplatesList(ctx context.Context, localVarOptionals *msx_platform_client.GetDeviceTemplatesListOpts) ([]msx_platform_client.DeviceTemplate, *http.Response, error) {
	ret := _m.Called(ctx, localVarOptionals)

	var r0 []msx_platform_client.DeviceTemplate
	if rf, ok := ret.Get(0).(func(context.Context, *msx_platform_client.GetDeviceTemplatesListOpts) []msx_platform_client.DeviceTemplate); ok {
		r0 = rf(ctx, localVarOptionals)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]msx_platform_client.DeviceTemplate)
		}
	}

	var r1 *http.Response
	if rf, ok := ret.Get(1).(func(context.Context, *msx_platform_client.GetDeviceTemplatesListOpts) *http.Response); ok {
		r1 = rf(ctx, localVarOptionals)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, *msx_platform_client.GetDeviceTemplatesListOpts) error); ok {
		r2 = rf(ctx, localVarOptionals)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateDeviceTemplateAccess provides a mock function with given fields: ctx, id, deviceTemplateAccess
func (_m *MockDeviceTemplatesApi) UpdateDeviceTemplateAccess(ctx context.Context, id string, deviceTemplateAccess msx_platform_client.DeviceTemplateAccess) (msx_platform_client.DeviceTemplateAccessResponse, *http.Response, error) {
	ret := _m.Called(ctx, id, deviceTemplateAccess)

	var r0 msx_platform_client.DeviceTemplateAccessResponse
	if rf, ok := ret.Get(0).(func(context.Context, string, msx_platform_client.DeviceTemplateAccess) msx_platform_client.DeviceTemplateAccessResponse); ok {
		r0 = rf(ctx, id, deviceTemplateAccess)
	} else {
		r0 = ret.Get(0).(msx_platform_client.DeviceTemplateAccessResponse)
	}

	var r1 *http.Response
	if rf, ok := ret.Get(1).(func(context.Context, string, msx_platform_client.DeviceTemplateAccess) *http.Response); ok {
		r1 = rf(ctx, id, deviceTemplateAccess)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string, msx_platform_client.DeviceTemplateAccess) error); ok {
		r2 = rf(ctx, id, deviceTemplateAccess)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
