// Code generated by mockery v2.3.0. DO NOT EDIT.

package platform

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	msx_platform_client "cto-github.cisco.com/NFV-BU/msx-platform-go-client"
)

// MockSecurityApi is an autogenerated mock type for the SecurityApi type
type MockSecurityApi struct {
	mock.Mock
}

// GetAccessToken provides a mock function with given fields: ctx, authorization, grantType, localVarOptionals
func (_m *MockSecurityApi) GetAccessToken(ctx context.Context, authorization string, grantType string, localVarOptionals *msx_platform_client.GetAccessTokenOpts) (msx_platform_client.AccessToken, *http.Response, error) {
	ret := _m.Called(ctx, authorization, grantType, localVarOptionals)

	var r0 msx_platform_client.AccessToken
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *msx_platform_client.GetAccessTokenOpts) msx_platform_client.AccessToken); ok {
		r0 = rf(ctx, authorization, grantType, localVarOptionals)
	} else {
		r0 = ret.Get(0).(msx_platform_client.AccessToken)
	}

	var r1 *http.Response
	if rf, ok := ret.Get(1).(func(context.Context, string, string, *msx_platform_client.GetAccessTokenOpts) *http.Response); ok {
		r1 = rf(ctx, authorization, grantType, localVarOptionals)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string, string, *msx_platform_client.GetAccessTokenOpts) error); ok {
		r2 = rf(ctx, authorization, grantType, localVarOptionals)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
