// Code generated by mockery v2.3.0. DO NOT EDIT.

package platform

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	msx_platform_client "cto-github.cisco.com/NFV-BU/msx-platform-go-client"
)

// MockWorkflowCategoriesApi is an autogenerated mock type for the WorkflowCategoriesApi type
type MockWorkflowCategoriesApi struct {
	mock.Mock
}

// CreateWorkflowCategory provides a mock function with given fields: ctx, workflowCategoryCreate, localVarOptionals
func (_m *MockWorkflowCategoriesApi) CreateWorkflowCategory(ctx context.Context, workflowCategoryCreate msx_platform_client.WorkflowCategoryCreate, localVarOptionals *msx_platform_client.CreateWorkflowCategoryOpts) (msx_platform_client.WorkflowCategory, *http.Response, error) {
	ret := _m.Called(ctx, workflowCategoryCreate, localVarOptionals)

	var r0 msx_platform_client.WorkflowCategory
	if rf, ok := ret.Get(0).(func(context.Context, msx_platform_client.WorkflowCategoryCreate, *msx_platform_client.CreateWorkflowCategoryOpts) msx_platform_client.WorkflowCategory); ok {
		r0 = rf(ctx, workflowCategoryCreate, localVarOptionals)
	} else {
		r0 = ret.Get(0).(msx_platform_client.WorkflowCategory)
	}

	var r1 *http.Response
	if rf, ok := ret.Get(1).(func(context.Context, msx_platform_client.WorkflowCategoryCreate, *msx_platform_client.CreateWorkflowCategoryOpts) *http.Response); ok {
		r1 = rf(ctx, workflowCategoryCreate, localVarOptionals)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, msx_platform_client.WorkflowCategoryCreate, *msx_platform_client.CreateWorkflowCategoryOpts) error); ok {
		r2 = rf(ctx, workflowCategoryCreate, localVarOptionals)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// DeleteWorkflowCategory provides a mock function with given fields: ctx, id
func (_m *MockWorkflowCategoriesApi) DeleteWorkflowCategory(ctx context.Context, id string) (*http.Response, error) {
	ret := _m.Called(ctx, id)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(context.Context, string) *http.Response); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWorkflowCategoriesList provides a mock function with given fields: ctx, localVarOptionals
func (_m *MockWorkflowCategoriesApi) GetWorkflowCategoriesList(ctx context.Context, localVarOptionals *msx_platform_client.GetWorkflowCategoriesListOpts) ([]msx_platform_client.WorkflowCategory, *http.Response, error) {
	ret := _m.Called(ctx, localVarOptionals)

	var r0 []msx_platform_client.WorkflowCategory
	if rf, ok := ret.Get(0).(func(context.Context, *msx_platform_client.GetWorkflowCategoriesListOpts) []msx_platform_client.WorkflowCategory); ok {
		r0 = rf(ctx, localVarOptionals)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]msx_platform_client.WorkflowCategory)
		}
	}

	var r1 *http.Response
	if rf, ok := ret.Get(1).(func(context.Context, *msx_platform_client.GetWorkflowCategoriesListOpts) *http.Response); ok {
		r1 = rf(ctx, localVarOptionals)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, *msx_platform_client.GetWorkflowCategoriesListOpts) error); ok {
		r2 = rf(ctx, localVarOptionals)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetWorkflowCategory provides a mock function with given fields: ctx, id
func (_m *MockWorkflowCategoriesApi) GetWorkflowCategory(ctx context.Context, id string) (msx_platform_client.WorkflowCategory, *http.Response, error) {
	ret := _m.Called(ctx, id)

	var r0 msx_platform_client.WorkflowCategory
	if rf, ok := ret.Get(0).(func(context.Context, string) msx_platform_client.WorkflowCategory); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(msx_platform_client.WorkflowCategory)
	}

	var r1 *http.Response
	if rf, ok := ret.Get(1).(func(context.Context, string) *http.Response); ok {
		r1 = rf(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateWorkflowCategory provides a mock function with given fields: ctx, id, workflowCategoryUpdate
func (_m *MockWorkflowCategoriesApi) UpdateWorkflowCategory(ctx context.Context, id string, workflowCategoryUpdate msx_platform_client.WorkflowCategoryUpdate) (msx_platform_client.WorkflowCategory, *http.Response, error) {
	ret := _m.Called(ctx, id, workflowCategoryUpdate)

	var r0 msx_platform_client.WorkflowCategory
	if rf, ok := ret.Get(0).(func(context.Context, string, msx_platform_client.WorkflowCategoryUpdate) msx_platform_client.WorkflowCategory); ok {
		r0 = rf(ctx, id, workflowCategoryUpdate)
	} else {
		r0 = ret.Get(0).(msx_platform_client.WorkflowCategory)
	}

	var r1 *http.Response
	if rf, ok := ret.Get(1).(func(context.Context, string, msx_platform_client.WorkflowCategoryUpdate) *http.Response); ok {
		r1 = rf(ctx, id, workflowCategoryUpdate)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string, msx_platform_client.WorkflowCategoryUpdate) error); ok {
		r2 = rf(ctx, id, workflowCategoryUpdate)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
