// Code generated by mockery v2.14.0. DO NOT EDIT.

package discovery

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRegistrationProvider is an autogenerated mock type for the RegistrationProvider type
type MockRegistrationProvider struct {
	mock.Mock
}

// Deregister provides a mock function with given fields: ctx
func (_m *MockRegistrationProvider) Deregister(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Register provides a mock function with given fields: ctx
func (_m *MockRegistrationProvider) Register(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockRegistrationProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRegistrationProvider creates a new instance of MockRegistrationProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRegistrationProvider(t mockConstructorTestingTNewMockRegistrationProvider) *MockRegistrationProvider {
	mock := &MockRegistrationProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
