{
 "title": "go-msx",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health Checks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "msx_health_checks_up", "legendFormat": "Up" },
    { "expr": "msx_health_checks_down", "legendFormat": "Down" },
    { "expr": "msx_health_checks_unknown", "legendFormat": "Unknown" }
   ]
  },
  { "title": "Consul", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Services Registered",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "msx_consul_registrations", "legendFormat": "Registrations" }
   ]
  },
  {
   "title": "Calls Per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(msx_consul_call_time_count[1m]) * 60.0",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(msx_consul_call_time_bucket[5m])) by (le))",
     "legendFormat": "{{api}} {{param}} 50%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(msx_consul_call_time_bucket[5m])) by (le))",
     "legendFormat": "{{api}} {{param}} 90%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(msx_consul_call_time_bucket[5m])) by (le))",
     "legendFormat": "{{api}} {{param}} 99%"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Sent Messages Per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(msx_stream_publisher_sends{binder=\"kafka\"}[1m]) * 60.0 ",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "rate(msx_stream_publisher_send_errors{binder=\"kafka\"}[1m]) * 60.0 ",
     "legendFormat": "{{topic}} Errors"
    }
   ]
  },
  {
   "title": "Received Messages Per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(msx_stream_subscriber_receives{binder=\"kafka\"}[5m]) * 300.0",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "rate(msx_stream_subscriber_receive_errors{binder=\"kafka\"}[5m]) * 300.0",
     "legendFormat": "{{topic}} errors"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "msx_stream_connections", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Subscriber Handler Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(msx_stream_subscriber_receive_time_bucket[5m])) by (le))",
     "legendFormat": "{{topic}} 50%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(msx_stream_subscriber_receive_time_bucket[5m])) by (le))",
     "legendFormat": "{{topic}} 90%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(msx_stream_subscriber_receive_time_bucket[5m])) by (le))",
     "legendFormat": "{{topic}} 99%"
    }
   ]
  },
  {
   "title": "Publish Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(msx_stream_publisher_send_time_bucket[5m])) by (le))",
     "legendFormat": "{{topic}} 50%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(msx_stream_publisher_send_time_bucket[5m])) by (le))",
     "legendFormat": "{{topic}} 90%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(msx_stream_publisher_send_time_bucket[5m])) by (le))",
     "legendFormat": "{{topic}} 99%"
    }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Redis Calls Per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(msx_redis_calls[1m]) * 60.0",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "rate(msx_redis_callErrors[1m]) * 60.0",
     "legendFormat": "{{ command }} errors"
    }
   ]
  },
  {
   "title": "Call Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(msx_redis_callTime_bucket[5m])) by (le))",
     "legendFormat": "{{ command }} 50%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(msx_redis_callTime_bucket[5m])) by (le))",
     "legendFormat": "{{command}} 90%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(msx_redis_callTime_bucket[5m])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  { "title": "Go", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Active Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_sys_bytes{job=\"go_msx\"}",
     "legendFormat": "Stack"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{job=\"go_msx\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{job=\"go_msx\"}",
     "legendFormat": "In-Use"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{job=\"go_msx\"}",
     "legendFormat": "Profiling Bucket Hash"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{job=\"go_msx\"}",
     "legendFormat": "GC"
    },
    {
     "expr": "go_memstats_other_sys_bytes{job=\"go_msx\"}",
     "legendFormat": "Other"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"go_msx\"}",
     "legendFormat": "Heap Alloc"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"go_msx\"}",
     "legendFormat": "Heap In-Use"
    }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_sys_bytes{job=\"go_msx\"}",
     "legendFormat": "Stack"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{job=\"go_msx\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{job=\"go_msx\"}",
     "legendFormat": "In-Use"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{job=\"go_msx\"}",
     "legendFormat": "Profiling Bucket Hash"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{job=\"go_msx\"}",
     "legendFormat": "GC"
    },
    {
     "expr": "go_memstats_other_sys_bytes{job=\"go_msx\"}",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"go_msx\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"go_msx\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"go_msx\"}",
     "legendFormat": "In-Use"
    }
   ]
  },
  {
   "title": "Heap Objects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_objects{job=\"go_msx\"}",
     "legendFormat": "Total Objects"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"go_msx\"}",
     "legendFormat": "Goroutines"
    },
    {
     "expr": "go_threads{job=\"go_msx\"}",
     "legendFormat": "Threads"
    }
   ]
  }
 ]
}