// Code generated by mockery v2.3.0. DO NOT EDIT.

package integration

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMsxContextServiceExecutor is an autogenerated mock type for the MsxContextServiceExecutor type
type MockMsxContextServiceExecutor struct {
	mock.Mock
}

// Context provides a mock function with given fields:
func (_m *MockMsxContextServiceExecutor) Context() context.Context {
	ret := _m.Called()

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// Execute provides a mock function with given fields: request
func (_m *MockMsxContextServiceExecutor) Execute(request *MsxEndpointRequest) (*MsxResponse, error) {
	ret := _m.Called(request)

	var r0 *MsxResponse
	if rf, ok := ret.Get(0).(func(*MsxEndpointRequest) *MsxResponse); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MsxResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*MsxEndpointRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
