// Code generated by mockery v2.3.0. DO NOT EDIT.

package integration

import mock "github.com/stretchr/testify/mock"

// MockMsxServiceExecutor is an autogenerated mock type for the MsxServiceExecutor type
type MockMsxServiceExecutor struct {
	mock.Mock
}

// Execute provides a mock function with given fields: request
func (_m *MockMsxServiceExecutor) Execute(request *MsxEndpointRequest) (*MsxResponse, error) {
	ret := _m.Called(request)

	var r0 *MsxResponse
	if rf, ok := ret.Get(0).(func(*MsxEndpointRequest) *MsxResponse); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MsxResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*MsxEndpointRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
