name: Index
on: push
jobs:
  Index:
    if: github.repository == 'cpx-saas/go-msx'
    runs-on: [ self-hosted, Linux ]
    container: sourcegraph/lsif-go:latest
    env:
      SRC_ENDPOINT: https://sg.infra.ciscomsx.com
      SRC_ACCESS_TOKEN: ${{ secrets.SRC_ACCESS_TOKEN }}
      INDEX_REPO: cto-github.cisco.com/NFV-BU/go-msx
    steps:
      - uses: actions/checkout@v1
      - name: Generate index
        run: lsif-go --no-animation
          --repository-remote="$INDEX_REPO"
      - name: Upload index
        run: src lsif upload
          -github-token=${{ secrets.ENTERPRISE_TOKEN }}
          -ignore-upload-failure
          -no-progress
          -repo $INDEX_REPO
