// Code generated by mockery v2.3.0. DO NOT EDIT.

package webservice

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockHttpHandler is an autogenerated mock type for the HttpHandler type
type MockHttpHandler struct {
	mock.Mock
}

// ServeHTTP provides a mock function with given fields: _a0, _a1
func (_m *MockHttpHandler) ServeHTTP(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}
