// Code generated by mockery v2.3.0. DO NOT EDIT.

package webservice

import (
	restful "github.com/emicklei/go-restful/v3"
	mock "github.com/stretchr/testify/mock"
)

// MockRestController is an autogenerated mock type for the RestController type
type MockRestController struct {
	mock.Mock
}

// Routes provides a mock function with given fields: svc
func (_m *MockRestController) Routes(svc *restful.WebService) {
	_m.Called(svc)
}
