// Code generated by mockery v2.3.0. DO NOT EDIT.

package webservice

import (
	restful "github.com/emicklei/go-restful"
	mock "github.com/stretchr/testify/mock"
)

// MockAuthenticationProvider is an autogenerated mock type for the AuthenticationProvider type
type MockAuthenticationProvider struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: request
func (_m *MockAuthenticationProvider) Authenticate(request *restful.Request) error {
	ret := _m.Called(request)

	var r0 error
	if rf, ok := ret.Get(0).(func(*restful.Request) error); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
