// Code generated by mockery v2.3.0. DO NOT EDIT.

package webservice

import (
	restful "github.com/emicklei/go-restful"
	mock "github.com/stretchr/testify/mock"
)

// MockDocumentationProvider is an autogenerated mock type for the DocumentationProvider type
type MockDocumentationProvider struct {
	mock.Mock
}

// Actuate provides a mock function with given fields: container, webService
func (_m *MockDocumentationProvider) Actuate(container *restful.Container, webService *restful.WebService) error {
	ret := _m.Called(container, webService)

	var r0 error
	if rf, ok := ret.Get(0).(func(*restful.Container, *restful.WebService) error); ok {
		r0 = rf(container, webService)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
